class MessageType:
    ADD_APP_USER_WEBSOCKET = "ADD_APP_USER_WEBSOCKET"
    REMOVE_APP_USER_WEBSOCKET = "REMOVE_APP_USER_WEBSOCKET"
    ROUTABLE = "ROUTABLE"
    FULL_SYNC = "FULL_SYNC"
    SERVER_MODE = "SERVER_MODE"
    SET_LAST_MESSAGE_READ = "SET_LAST_MESSAGE_READ"
    OFFLINE_NOTIFICATION = "OFFLINE_NOTIFICATION"
    SYSTEM_ROUTABLE = "SYSTEM_ROUTABLE"
